version: '3'

name: larascript

services:
  mongodb:
    container_name: larascript-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      LARASCRIPT_DEFAULT_CREDENTIALS: mongodb://root:example@localhost:27017/app?authSource=admin
    volumes:
      - mongodb_data:/data/db
      - mongodb_keyfile:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "admin", "-u", "root", "-p", "example", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
  mongodb_keyfile:

networks:
  app-network:
    external: true
    name: larascript