version: '3'

services:
  mongodb:
    container_name: larascript-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      LARASCRIPT_DEFAULT_CREDENTIALS: mongodb://root:example@localhost:27017/app?authSource=admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data: