services:
  api:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
