# ./larascript-node/docker/mongodb/Dockerfile

# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Start the MongoDB service
CMD ["mongod"]
